name: Java CI with Gradle

on:
  push:
    branches: ci-gradle-test
  pull_request:
    branches: ci-gradle-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
      - name: Build with Gradle
        run: ./gradlew build
